### API YOLO

GET http://localhost:3000/

###

#### DEVICES LOCATIONS

### getDevicesInLocation
GET http://localhost:3000/locations/1/devices

###

### updateDevicesInLocation
PUT http://localhost:3000/locations/3/devices
Content-Type: application/json

{
    "id_device": [43]
}



###



