### API YOLO

GET http://localhost:3000/

###

#### INBOX DEVICES

### getInbox
GET http://localhost:3000/inbox

###

### getScanNoInbox
GET http://localhost:3000/inbox/scan

###

### getDevices
GET http://localhost:3000/devices

###

### getDeviceId
GET http://localhost:3000/devices/1

###

### createDevice
POST http://localhost:3000/devices
Content-Type: application/json

    {
    "label": "lãmpada",
    "openhab_uid": "tuya:tuyaDevice:ebae0d2627f876236ccpge"
    }

###

### replaceDevice
PUT http://localhost:3000/devices/1/replace
Content-Type: application/json

    {
    "device_id": 1,
    "openhab_uid": "tuya:tuyaDevice:ebae0d2627f876236ccpge"
    }

###

#### updateDeviceProperties
PUT http://localhost:3000/devices/1/properties
Content-Type: application/json

    {
    "name": "toggle",
    "data": {"toggle_on": false}
    }

###




