### API YOLO

GET http://localhost:3000/

###

#### LOCATIONS

### getLocations
GET http://localhost:3000/locations

###

### getLocationTypes
GET http://localhost:3000/locations/location-types

###

### createLocation
POST http://localhost:3000/locations
Content-Type: application/json

    {
        "label": "Yolo",
        "location_type": "BUILDING",
        "parent_location_id": null
    }

###

### updateLocation
PUT http://localhost:3000/locations/1
Content-Type: application/json

    {
        "label": "Prédio Boa Viagem",
        "location_type": "BUILDING",
        "parent_location_id": null
    }

###

### deleteLocation
DELETE http://localhost:3000/locations/1
Content-Type: application/json

###

